nelmio_api_doc:
    documentation:
        info:
            title: STEM Scorekeeping App
            description: This app keeps scores for all sports events happening on STEM Games.
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
